# Generated by Django 5.2.8 on 2025-11-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ELECTRONICA', 'Electrónica'), ('COMPUTACION', 'Computación'), ('ACCESORIOS', 'Accesorios'), ('OTROS', 'Otros')], default='OTROS', max_length=50),
        ),
    ]
